# Generated by Django 6.0.7 on 2026-07-24 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=150)),
                ('latitude', models.FloatField(default=13.0827)),
                ('longitude', models.FloatField(default=80.2707)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='bookings.pickuprequest')),
            ],
        ),
    ]
