# Generated by Django 6.0.7 on 2026-07-24 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('is_operational', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PickupSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('slot_time', models.CharField(help_text='e.g. 09:00 AM - 12:00 PM', max_length=50)),
                ('max_capacity', models.PositiveIntegerField(default=20)),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postal_code_prefix', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(help_text='e.g. Office to Warehouse Daily', max_length=100)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('package_category', models.CharField(choices=[('DOCUMENTS', 'Documents & Letters'), ('ELECTRONICS', 'Electronics & Gadgets'), ('CLOTHING', 'Clothing & Apparel'), ('FRAGILE', 'Fragile & Glassware'), ('FOOD_PERISHABLE', 'Food & Perishables'), ('HEAVY_CARGO', 'Heavy / Large Cargo'), ('OTHER', 'Other Merchandise')], default='DOCUMENTS', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Agent Assignment'), ('ASSIGNED', 'Agent Assigned'), ('ON_THE_WAY', 'Agent On The Way'), ('PICKED', 'Package Picked Up'), ('SORTING', 'Sorting Center'), ('TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('pickup_contact_name', models.CharField(max_length=100)),
                ('pickup_phone', models.CharField(max_length=20)),
                ('pickup_address', models.TextField()),
                ('pickup_lat', models.FloatField(default=13.0827)),
                ('pickup_lng', models.FloatField(default=80.2707)),
                ('delivery_contact_name', models.CharField(max_length=100)),
                ('delivery_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_lat', models.FloatField(default=13.09)),
                ('delivery_lng', models.FloatField(default=80.28)),
                ('package_name', models.CharField(max_length=150)),
                ('package_category', models.CharField(choices=[('DOCUMENTS', 'Documents & Letters'), ('ELECTRONICS', 'Electronics & Gadgets'), ('CLOTHING', 'Clothing & Apparel'), ('FRAGILE', 'Fragile & Glassware'), ('FOOD_PERISHABLE', 'Food & Perishables'), ('HEAVY_CARGO', 'Heavy / Large Cargo'), ('OTHER', 'Other Merchandise')], default='DOCUMENTS', max_length=30)),
                ('package_image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('approx_weight_kg', models.FloatField(default=1.0)),
                ('package_size', models.CharField(default='Small (0.5m x 0.5m)', max_length=50)),
                ('is_fragile', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_slot_time', models.CharField(default='09:00 AM - 12:00 PM', max_length=50)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('qr_code_str', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
