# Generated by Django 6.0.7 on 2026-07-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='pickup_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='qr_code_str',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Agent Assignment'), ('ASSIGNED', 'Agent Assigned'), ('ON_THE_WAY', 'Agent On The Way'), ('PICKED', 'Package Picked Up'), ('SORTING', 'Sorting Center'), ('TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='tracking_number',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
