version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cps_postgres
    environment:
      POSTGRES_DB: courier_db
      POSTGRES_USER: courier_user
      POSTGRES_PASSWORD: courier_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cps_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: cps_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-courier-pickup-scheduler-prod-key
      - DEBUG=1
      - DATABASE_URL=postgres://courier_user:courier_secure_password@db:5432/courier_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./backend
    container_name: cps_celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  frontend:
    build: ./frontend
    container_name: cps_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data:
