# Generated by Django 6.0.7 on 2026-07-24 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfPickup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_data_url', models.TextField(help_text='Base64 Canvas Signature string')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('voice_note_text', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='bookings.pickuprequest')),
            ],
        ),
    ]
