# Generated by Django 6.0.7 on 2026-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Pickup Agent'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
